# fly.toml app configuration file generated for markdown-dingus on 2025-07-19T10:13:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markdown-dingus'
primary_region = 'iad'

[build]

[env]
  DINGUS_BIND_ADDRESS = '0.0.0.0:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
