name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: shuttle-hq/deploy-action@v2
      with:
        shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
        project-id: proj_01JQBMMEKCKS9VWFEV8MGEE3TG
