name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure toolchain
      run: |
        rustup toolchain install stable --profile minimal --no-self-update -c clippy
        rustup default stable

    - name: Check
      run: cargo check
